/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 93501e72291b69104ef08aaa620d085e)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  AI: Ai;
  PiAgent: DurableObjectNamespace<import("./src/server").PiAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "PiAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
